import { converter, parse, type Lab, type Lab65, type Rgb } from 'culori';
import rgbSpace from 'color-space/rgb.js';
import xyzSpace from 'color-space/xyz.js';
import 'color-space/lab.js';
import { gameProfile } from './gameProfile';

export type ModelLab = Lab | Lab65;
const culoriLab = converter('lab');
const culoriRgb = converter('rgb');

export function labPoint(l: number, a: number, b: number): ModelLab {
  return { mode: gameProfile() === 'ryan' ? 'lab65' : 'lab', l, a, b };
}

export function normalizeHex(input: string): string {
  let value = input.trim().replace(/^#/, '');
  if (/^[\da-f]{3}$/i.test(value)) value = [...value].map(c => c + c).join('');
  if (!/^[\da-f]{6}$/i.test(value)) throw new Error('Enter a dictionary name or a 3- or 6-digit hex color.');
  return '#' + value.toUpperCase();
}

export function hexToLab(hex: string): ModelLab {
  const normalized = normalizeHex(hex);
  if (gameProfile() === 'ryan') {
    return ryanRgbBytesToLab([1, 3, 5].map(i => parseInt(normalized.slice(i, i + 2), 16)));
  }
  return culoriLab(parse(normalized)!)!;
}

export function rgbToLab(r: number, g: number, b: number): ModelLab {
  if (gameProfile() === 'osmanyo') return culoriLab({ mode: 'rgb', r, g, b })!;
  return ryanRgbBytesToLab([r * 255, g * 255, b * 255]);
}

function ryanRgbBytesToLab(channels: number[]): Lab65 {
  // This is the rgb -> xyz -> lab route generated by color-space@2.3.2.
  // Its constants and thresholds match Ryan's deployed forward conversion.
  const [l, a, bb] = xyzSpace.lab(rgbSpace.xyz(channels));
  return { mode: 'lab65', l, a, b: bb };
}

export function toRgb(lab: ModelLab): Rgb {
  if (lab.mode === 'lab') return culoriRgb(lab)!;
  // Geometry-only inverse of the deployed forward conversion. color-space's
  // bundled inverse has a low-light branch bug, so invert the forward mapping.
  const f = (lab.l + 16) / 116;
  const inverse = (v: number) => v ** 3 > 0.008856 ? v ** 3 : (v - 16 / 116) / 7.787;
  return culoriRgb({
    mode: 'xyz65',
    x: 0.95047 * inverse(f + lab.a / 500),
    y: inverse(f),
    z: 1.08883 * inverse(f - lab.b / 200),
  })!;
}

export function inGamut(lab: ModelLab, tolerance = 0.00001): boolean {
  const rgb = toRgb(lab);
  return [rgb.r, rgb.g, rgb.b].every(v => v >= -tolerance && v <= 1 + tolerance);
}
